---
# tasks file for deploy

- name:  update package
  apt:
    update_cache: yes

- name: copying html file apache2 server
  copy:
     src: shiva.html
     dest: /var/www/html/shiva.html

- name: copying php file to apache server
  copy:
     src: info.php
     dest: /var/www/html/info.php
  notify: 
   - restart apache2
