---
 - hosts: all
   become: yes
   gather_facts: no

   tasks: 
  
   - name:  update package
     apt:
      update_cache: yes 

   - name: Install list of packages
     apt: name={{item}} state=present
     with_items:
          - git
          - nano
          - vim
          - php
          - libapache2-mod-php
          - php-mcrypt
          - php-mysql
